package org.example.ihm.enums.navigation;

public enum BackMenuOptions {
    CLOSE_PROGRAM,
    NO_RETURN,
    RETURN_TO_MAIN_MENU,
    RETURN_TO_ARTICLE_GESTION_MENU,
    RETURN_TO_INVENTORY_CONSULT_MENU,
    RETURN_TO_SALE_GESTION_MENU,
    RETURN_TO_CLIENT_GESTION_MENU,
    RETURN_TO_SALE_REPORT_AND_ANALYSIS_MENU
}
