package org.example.ihm.enums.navigation;

public enum MenuType {
    MAIN_MENU,
    ARTICLE_GESTION_MENU,
    SALE_GESTION_MENU,
    CLIENT_GESTION_MENU,
    SALE_REPORT_AND_ANALYSIS_MENU,
    ARTICLE_CREATION_MENU,
    ARTICLE_CONSULT_MENU,
    SALE_MENU,
    CLIENT_CONSULT_MENU,
    SALE_BY_PERIOD_MENU,
    CLIENT_UPDATE_MENU,
    CLOTHE_CATEGORY_MENU,
    CLOTHE_SIZE_MENU,
    ARTICLE_UPDATE_MENU,
    CLOTHE_UPDATE_MENU,
    ELECTRONIC_UPDATE_MENU,
    FOOD_UPDATE_MENU
}
